# Generated by Django 4.0.4 on 2022-06-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_buyer_delete_seller_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанная позиция', 'verbose_name_plural': 'Список заказанных позиций'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Список информации о продукте'},
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='price_rrc',
            field=models.PositiveIntegerField(default=0, verbose_name='Рекомендуемая розничная цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_infos', to='backend.product', verbose_name='название'),
        ),
    ]
